import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def run_abm_4_strategies(params, initial_props, steps=3000, noise_beta=1.0):
    # -----------------------------
    # Global parameters (model primitives)
    # -----------------------------
    N = params['N']              # Total number of agents (finite population size)
    alpha = params['alpha']      # Probability a paper is of high quality (Pr(q=1))
    K_rev = params['K_rev']      # Review capacity (max papers that can be effectively reviewed)
    K_store = params['K_store']  # Publication capacity (number of available journal slots K)
    r = params['r']              # Reward from successful publication (reputation / payoff)
    c = params['c']              # Cost of submission (effort, time, revision cost)
    lam = params['lam']          # Probability bad paper is correctly rejected (screening accuracy)
    eps = params['eps']          # Probability good paper is wrongly rejected (review error)

    # -----------------------------
    # Initial population setup
    # -----------------------------
    # initial_props: [prop_OG, prop_AS, prop_OB, prop_NS]
    counts = [int(p * N) for p in initial_props]

    # Adjust rounding error so total population = N
    counts[0] += N - sum(counts)

    # Strategy encoding:
    # 0 = OG (Only Good)     -> submit only high-quality papers
    # 1 = AS (Always Submit) -> submit regardless of quality
    # 2 = OB (Only Bad)      -> submit only low-quality papers
    # 3 = NS (Never Submit)  -> never submit
    population = np.array(
        [0]*counts[0] + [1]*counts[1] + [2]*counts[2] + [3]*counts[3]
    )
    np.random.shuffle(population)

    # Store time evolution of strategy proportions
    history = {0: [], 1: [], 2: [], 3: []}

    # -----------------------------
    # Main simulation loop
    # -----------------------------
    for t in range(steps):
        # Current number of agents per strategy
        pop_counts = np.bincount(population, minlength=4)
        n_og, n_as, n_ob, n_ns = pop_counts

        # Record proportions over time
        history[0].append(n_og / N)
        history[1].append(n_as / N)
        history[2].append(n_ob / N)
        history[3].append(n_ns / N)

        # -----------------------------
        # Stage 1: Submission volumes
        # -----------------------------
        # Good submissions (q=1) generated by OG and AS
        V_G = alpha * (n_og + n_as)

        # Bad submissions (q=0) generated by AS and OB
        V_B = (1 - alpha) * (n_as + n_ob)

        # Total submission volume
        V = V_G + V_B

        # -----------------------------
        # Stage 2: Peer review filtering
        # -----------------------------
        # Effective review intensity (processing rate)
        # If submissions exceed capacity, review quality degrades
        eta = min(1.0, K_rev / V) if V > 0 else 1.0

        # Probability a good paper passes peer review
        # (affected by false rejection rate eps)
        pi_1 = 1 - eta * eps

        # Probability a bad paper passes peer review
        # (affected by screening accuracy lam)
        pi_0 = 1 - eta * (1 - lam)

        # Number of papers that pass peer review
        M_G = V_G * pi_1   # accepted good papers
        M_B = V_B * pi_0   # accepted bad papers
        M = M_G + M_B      # total peer-accepted papers

        # -----------------------------
        # Stage 3: Publication capacity constraint
        # -----------------------------
        # Rationing probability (uniform selection among accepted papers)
        # If M > K_store, only a fraction rho are published
        rho = min(1.0, K_store / M) if M > 0 else 1.0

        # -----------------------------
        # Stage 4: Payoff computation
        # -----------------------------
        # Expected payoff from a single submission outcome

        # For good papers
        Pi_good = r * rho * pi_1 - c

        # For bad papers
        Pi_bad = r * rho * pi_0 - c

        # Strategy-level expected utilities
        U_OG = alpha * Pi_good                       # only produces good papers
        U_AS = alpha * Pi_good + (1 - alpha) * Pi_bad # produces both types
        U_OB = (1 - alpha) * Pi_bad                  # only produces bad papers
        U_NS = 0.0                                  # no submission, no payoff

        payoffs = np.array([U_OG, U_AS, U_OB, U_NS])

        # -----------------------------
        # Stage 5: Strategy update (Fermi imitation)
        # -----------------------------
        # Fraction of population that updates strategy per step
        num_revise = int(0.02 * N)

        # Randomly select updating agents
        indices = np.random.choice(N, num_revise, replace=False)

        # Randomly select role models (opponents)
        opponents = np.random.choice(N, num_revise, replace=True)

        for idx, opp in zip(indices, opponents):
            s_i = population[idx]
            s_j = population[opp]
            
            if s_i != s_j:
                payoff_i = payoffs[s_i]
                payoff_j = payoffs[s_j]
                
                # Fermi update rule (bounded rationality)
                # Probability of adopting opponent's strategy
                prob_switch = 1 / (1 + np.exp(-noise_beta * (payoff_j - payoff_i)))

                if np.random.random() < prob_switch:
                    population[idx] = s_j

    return history


# --- Configuration ---
params_A = {'N': 1000, 'alpha': 0.2, 'K_rev': 300, 'K_store': 400, 'r': 100, 'c': 25, 'lam': 0.1, 'eps': 0.05}
params_B = {'N': 1000, 'alpha': 0.2, 'K_rev': 1200, 'K_store': 180, 'r': 150, 'c': 30, 'lam': 0.4, 'eps': 0.01}

# Initialize with 25% of each strategy to prove OB and NS die out
initial_mix = [0.25, 0.25, 0.25, 0.25] 

print("Running 4-strategy simulations...")
steps = 3000
history_A = run_abm_4_strategies(params_A, initial_mix, steps=steps)
history_B = run_abm_4_strategies(params_B, initial_mix, steps=steps)

# --- Save to CSV ---
df = pd.DataFrame({
    'Step': range(steps),
    'ScenA_OG': history_A[0], 'ScenA_AS': history_A[1], 'ScenA_OB': history_A[2], 'ScenA_NS': history_A[3],
    'ScenB_OG': history_B[0], 'ScenB_AS': history_B[1], 'ScenB_OB': history_B[2], 'ScenB_NS': history_B[3]
})
df.to_csv('simulation_4_strategies.csv', index=False)
print("Saved data to simulation_4_strategies.csv")

# --- Plotting & Save as PDF ---
data = pd.read_csv('simulation_4_strategies.csv')

# Plot Scenario A
plt.figure(figsize=(8, 6))
plt.plot(data['Step'], data['ScenA_OG'], label='Only Good (OG)', color='green', linewidth=2)
plt.plot(data['Step'], data['ScenA_AS'], label='Always Submit (AS)', color='red', linewidth=2)
plt.plot(data['Step'], data['ScenA_OB'], label='Only Bad (OB)', color='orange', linestyle='--', linewidth=1.5)
plt.plot(data['Step'], data['ScenA_NS'], label='Never Submit (NS)', color='gray', linestyle='--', linewidth=1.5)
plt.title('Scenario A: 4 Strategies Collapse to Bistability\n(Equal Start)', fontsize=14)
plt.xlabel('Time Steps', fontsize=12)
plt.ylabel('Proportion of Authors', fontsize=12)
plt.ylim(-0.05, 1.05)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('Scenario_A_4_Strategies.pdf')

# Plot Scenario B
plt.figure(figsize=(8, 6))
plt.plot(data['Step'], data['ScenB_OG'], label='Only Good (OG)', color='green', linewidth=2)
plt.plot(data['Step'], data['ScenB_AS'], label='Always Submit (AS)', color='red', linewidth=2)
plt.plot(data['Step'], data['ScenB_OB'], label='Only Bad (OB)', color='orange', linestyle='--', linewidth=1.5)
plt.plot(data['Step'], data['ScenB_NS'], label='Never Submit (NS)', color='gray', linestyle='--', linewidth=1.5)
plt.title('Scenario B: 4 Strategies Converge to Stable Coexistence\n(Equal Start)', fontsize=14)
plt.xlabel('Time Steps', fontsize=12)
plt.ylabel('Proportion of Authors', fontsize=12)
plt.ylim(-0.05, 1.05)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('Scenario_B_4_Strategies.pdf')
print("Saved PDF plots.")